---

### Initial Setup of both hosts ###
- hosts: jenkins,pipeline
  become: yes

  roles:
    - role: './firewall_start'
    - role: './java'
    - role: './docker1_ubuntu'
    - role: './docker_registry'

### Setting up the pipeline host (AKA Jenkins agent host) ###
- hosts: pipeline
  become: yes

  roles:
    - role: './sphinx_container'
    - role: './sphinx_html'
    - role: './prod_sphinx_html'

### Setting up Jenkins host now that the pipeline host is ready (Jenkins will try to connect to it) ###
- hosts: jenkins
  become: yes

  roles:
    - role: './jenkins'

### Locking down both hosts ###
- hosts: jenkins,pipeline
  become: yes

  roles:
    - role: './firewall_lockdown'