---

- hosts: jenkins,pipeline
  become: yes

  roles:
    - role: './firewall_start'
    - role: './java'
    - role: './docker1_ubuntu'
    - role: './docker_registry'

- hosts: pipeline
  become: yes

  roles:
    #- role: './jenkins_agent'
    - role: './sphinx_container'
    - role: './sphinx_html'
    - role: './prod_sphinx_html'

- hosts: jenkins
  become: yes

  roles:
    - role: './jenkins'


- hosts: jenkins,pipeline
  become: yes

  roles:
    - role: './firewall_lockdown'