---

- name: UFW - Allow HTTP on 8080
  community.general.ufw:
    rule: allow
    port: '8080'

- name: Pull an image
  community.docker.docker_image:
    name: httpd:2.4.53
    source: pull

- name: Push to local registry
  community.docker.docker_image:
    name: httpd:2.4.53
    repository: localhost:5000/httpd:2.4.53
    push: yes
    source: local

- name: Run Apache Server with Rendered Sphinx Doc
  docker_container:
    detach: true
    name: "sphinx-html"
    published_ports: ["8080:80"]
    image: localhost:5000/httpd:2.4.53
    volumes:
      - /docs/_build/html/:/usr/local/apache2/htdocs/

