---


- name: UFW - Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'

- name: UFW - Allow Jenkins Communication
  community.general.ufw:
    rule: allow
    port: '50000'

- name: Create Mount Directory for Jenkins
  ansible.builtin.file:
    path: /var/jenkins_home
    state: directory
    mode: '0777'

- name: Copy configuration file for Jenkins
  ansible.builtin.copy:
    src: "jenkins.yml"
    dest: "/var/jenkins_home/jenkins.yml"

- name: Copy SSH key for Jenkins credential
  ansible.builtin.copy:
    src: "project"
    dest: "/var/jenkins_home/project"

- name: Copy config for Jenkins Jenkins Pipeline
  ansible.builtin.copy:
    src: "pipeline_config.xml"
    dest: "/var/jenkins_home/pipeline_config.xml"

- name: Jenkins Container
  docker_container:
    name: jenkins
    image:  bitnami/jenkins:latest
    #image:  jenkins/jenkins:lts-jdk11
    published_ports: ["80:8080","50000:50000"]
    restart_policy: "always"
    env:
      JENKINS_USERNAME=admin
      JENKINS_PASSWORD=my_password
      CASC_JENKINS_CONFIG=/bitnami/jenkins/home/jenkins.yml
      #JENKINS_SKIP_BOOTSTRAP=yes

- name: Pause for Jenkins to start up
  pause:
    seconds: 90 #really does take this long on t2.micro, otherwise the next task fails to install plugin

- name: Copy SSH
  shell: docker cp /var/jenkins_home/project jenkins:/bitnami/jenkins/home/project

- name: Copy Jenkins Config
  shell: docker cp /var/jenkins_home/jenkins.yml jenkins:/bitnami/jenkins/home/jenkins.yml

- name: mkdir2
  shell: docker exec -it jenkins mkdir /bitnami/jenkins/home/jobs/pipeline

- name: Copy pipeline
  shell: docker cp /var/jenkins_home/pipeline_config.xml jenkins:/bitnami/jenkins/home/jobs/pipeline/config.xml


- name: Install configuration-as-code plugin for Jenkins
  community.general.jenkins_plugin:
    name: configuration-as-code
    url_username: admin
    url_password: my_password
    url: http://localhost:80

- name: Install configuration-as-code-groovy plugin for Jenkins
  community.general.jenkins_plugin:
    name: configuration-as-code-groovy
    url_username: admin
    url_password: my_password
    url: http://localhost:80

- name: Restart Jenkins container
  community.docker.docker_container:
    name: jenkins
    state: started
    restart: yes
