---


- name: UFW - Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'

- name: UFW - Allow Jenkins Communication
  community.general.ufw:
    rule: allow
    port: '50000'

- name: Jenkins Container
  docker_container:
    name: jenkins
    image:  bitnami/jenkins:latest
    published_ports: ["80:8080","50000:50000"]
    restart_policy: "always"
    volumes:
      - jenkins_home:/var/jenkins_home
    env:
      JENKINS_USERNAME=admin
      JENKINS_PASSWORD=my_password

- name: Pause for Jenkins to start up
  pause:
    seconds: 30

