---


# - name: Create Mount Directory for Ephillips-Homepage
#   ansible.builtin.file:
#     path: /opt/mounts/Ephillips-Homepage
#     state: directory
#     mode: '0755'    

# - name: Copy files for Ephillips-Homepage
#   ansible.builtin.copy:
#     src: "../files/home/" #"{{ playbook_dir }}/../http-site/home/"
#     dest: "/opt/mounts/Ephillips-Homepage/"

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    name: HTTP

- name: Jenkins Container
  docker_container:
    name: jenkins
    image:  bitnami/jenkins:latest
    published_ports: ["80:8080","50000:50000"]
    restart_policy: "always"
    volumes:
      - jenkins_home:/var/jenkins_home
    env:
      JENKINS_USERNAME=admin
      JENKINS_PASSWORD=my_password

