---


- name: UFW - Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'

- name: UFW - Allow Jenkins Communication
  community.general.ufw:
    rule: allow
    port: '50000'

- name: Create Mount Directory for Jenkins
  ansible.builtin.file:
    path: /var/jenkins_home
    state: directory
    mode: '0775'    

- name: Copy configuration files for Jenkins
  ansible.builtin.copy:
    src: "jenkins.yml" #"{{ playbook_dir }}/../http-site/home/"
    dest: "/var/jenkins_home/jenkins.yml"

- name: Copy SSH key for Jenkins credential
  ansible.builtin.copy:
    src: "project"
    dest: "/var/jenkins_home/project"

- name: Jenkins Container
  docker_container:
    name: jenkins
    #image:  bitnami/jenkins:latest
    image:  jenkins/jenkins:lts-jdk11
    published_ports: ["80:8080","50000:50000"]
    restart_policy: "always"
    # volumes:
    #   - jenkins_home:/var/jenkins_home
    #   ##- /var/jenkins_home:/var/jenkins_home
    mounts:
      - source: "/var/jenkins_home"
        target: "/var/jenkins_home/"
        type: bind      
    env:
      JENKINS_USERNAME=admin
      JENKINS_PASSWORD=my_password
      JENKINS_HOME=/var/jenkins_home
      CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yml
      #JENKINS_SKIP_BOOTSTRAP=yes

- name: Pause for Jenkins to start up
  pause:
    seconds: 90 #really does take this long on t2.micro, otherwise the next task fails to install plugin

- name: Install configuration-as-code plugin for Jenkins
  community.general.jenkins_plugin:
    name: configuration-as-code
    url_username: admin
    url_password: my_password
    url: http://localhost:80

- name: Install configuration-as-code-groovy plugin for Jenkins
  community.general.jenkins_plugin:
    name: configuration-as-code-groovy
    url_username: admin
    url_password: my_password
    url: http://localhost:80

- name: Restart Jenkins container
  community.docker.docker_container:
    name: jenkins
    state: started
    restart: yes
