---

- name: Pull an image
  community.docker.docker_image:
    name: sphinxdoc/sphinx-latexpdf:4.5.0
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    # pull:
    #   platform: amd64

- name: Push to local registry
  community.docker.docker_image:
    name: sphinxdoc/sphinx-latexpdf:4.5.0
    repository: localhost:5000/sphinx-latexpdf:4.5.0
    push: yes
    source: local

- name: Create a Docs directory if it does not exist
  file:
    path: /docs
    state: directory
    mode: '0755'

- name: Run the Official Sphinx Container
  docker_container:
    detach: true
    name: "sphinx"
    image: localhost:5000/sphinx-latexpdf:4.5.0
    volumes:
      - /docs:/docs
#   register: docker_container_output

# - name: Show Container Status
#   debug:
#     msg: "{{ docker_container_output.container }}"

    