---

- name: Pull an image
  community.docker.docker_image:
    name: sphinxdoc/sphinx-latexpdf:4.5.0
    source: pull

- name: Push to local registry
  community.docker.docker_image:
    name: sphinxdoc/sphinx-latexpdf:4.5.0
    repository: localhost:5000/sphinx-latexpdf:4.5.0
    push: yes
    source: local

- name: Create a Docs directory if it does not exist
  file:
    path: /docs
    state: directory
    mode: '0755'

- name: Run the Official Sphinx Container
  docker_container:
    detach: true
    name: "sphinx"
    image: localhost:5000/sphinx-latexpdf:4.5.0
    volumes:
      - /docs:/docs

#Required for unit tests later
- name: Install BeautifulSoup4 python package
  pip:
    name: BeautifulSoup4

#copy the ip.txt file so we can reference it to make vars for the pipeline
- name: Copy ip.txt file with public IPs
  ansible.builtin.copy:
    src: "../../ip.txt"
    dest: "/var/ip.txt"
    